class Vocab {
  final int id;
  final String type;
  final String arabicMain;
  final String fusha; //
  final String englishMain;
  final String englishMaincom;
  final String english2;
  final String english2com;
  final String english3;
  final String english3com;
  final String english4;
  final String english4com;
  final String syn1; //
  final String syn2; //
  final String syn3; //
  final String verb;
  final String verbEng;
  //final String nomVerbPastAra;
  //final String nomVerbPastEng;
  //final String nomVerbPresAra;
  //final String nomVerbPresEng;
  final String nomVerbType; //
  final String nomVerbAra; //
  final String nomVerbEng; //
  final String noun;
  final String nounEng;
  final String adjective;
  final String adjectiveEng;
  final String masder;
  final String masderENG;
  final String ex1ENG;
  final String ex1ARA;
  final String ex2ENG;
  final String ex2ARA;
  final String ex3ENG;
  final String ex3ARA;
  //final String vERBprepositions;
  final String vERBprep1; //
  final String vERBprep1com; //
  final String vERBprep2; //
  final String vERBprep2com; //
  final String vERBprep3; //
  final String vERBprep3com; //
  final String vERBform;
  final String nOUNtype;
  final String nOUNplural;
  final String nounpluralType;
  final String aDJECTIVEmale;
  final String aDJECTIVEfemale;
  final String aDJECTIVEplMale;
  final String aDJECTIVEplFemale;
  final String aDJECTIVEpl;
  final String aDJECTIVEpltype;
  final String pREPex1ENG;
  final String pREPex1ARA;
  final String pREPex2ENG;
  final String pREPex2ARA;
  final String pREPex3ENG;
  final String pREPex3ARA;
  final String pREPex4ENG;
  final String pREPex4ARA;
  final String lvl;
  final String mp3ID;
  final String nomVerbAct;
  final String nomVerbActEng;
  final String nomVerbPas;
  final String nomVerbPasEng;


  const Vocab({
    required this.id,
    required this.type,
    required this.arabicMain,
    required this.fusha, //
    required this.englishMain,
    required this.englishMaincom,
    required this.english2,
    required this.english2com,
    required this.english3,
    required this.english3com,
    required this.english4,
    required this.english4com,
    required this.syn1, //
    required this.syn2, //
    required this.syn3, //
    required this.verb,
    required this.verbEng,
 /*   required this.nomVerbPastAra,
    required this.nomVerbPastEng,
    required this.nomVerbPresAra,
    required this.nomVerbPresEng,*/
    required this.nomVerbType, //
    required this.nomVerbAra, //
    required this.nomVerbEng, //
    required this.noun,
    required this.nounEng,
    required this.adjective,
    required this.adjectiveEng,
    required this.masder,
    required this.masderENG,
    required this.ex1ENG,
    required this.ex1ARA,
    required this.ex2ENG,
    required this.ex2ARA,
    required this.ex3ENG,
    required this.ex3ARA,
   // required this.vERBprepositions,
    required this.vERBprep1, //
    required this.vERBprep1com, //
    required this.vERBprep2, //
    required this.vERBprep2com, //
    required this.vERBprep3, //
    required this.vERBprep3com, //
    required this.vERBform,
    required this.nOUNtype,
    required this.nOUNplural,
    required this.nounpluralType,
    required this.aDJECTIVEpl,
    required this.aDJECTIVEmale,
    required this.aDJECTIVEfemale,
    required this.aDJECTIVEplMale,
    required this.aDJECTIVEplFemale,
    required this.aDJECTIVEpltype,
    required this.pREPex1ENG,
    required this.pREPex1ARA,
    required this.pREPex2ENG,
    required this.pREPex2ARA,
    required this.pREPex3ENG,
    required this.pREPex3ARA,
    required this.pREPex4ENG,
    required this.pREPex4ARA,
    required this.lvl,
    required this.mp3ID,
    required this.nomVerbAct,
    required this.nomVerbActEng,
    required this.nomVerbPas,
    required this.nomVerbPasEng,


  });

}

// Auto-generated by Firefoo v1.5.5 on 2022-11-24 11:04:04 UTC

class TestV {
  String arabic1;
  String arabic2;
  String arabic3;
  String arabic4;
  String englisch1;
  String englisch2;
  String englisch3;
  String englisch4;
  String englisch5;
  String englisch6;
  String englisch7;
  String englisch8;
  String forms1;
  String forms2;
  String forms3;
  int id;
  TestV({
    required this.arabic1,
    required this.arabic2,
    required this.arabic3,
    required this.arabic4,
    required this.englisch1,
    required this.englisch2,
    required this.englisch3,
    required this.englisch4,
    required this.englisch5,
    required this.englisch6,
    required this.englisch7,
    required this.englisch8,
    required this.forms1,
    required this.forms2,
    required this.forms3,
    required this.id,
  });


}